changelog:
  categories:
    - title: Breaking Changes 🪅
      labels:
        - 'breaking 💔'

    - title: New Features 🎉
      labels:
        - 'enhancement ➕'

    - title: 'Bugfixes 🐛'
      labels:
        - 'bug 🐛'

    - title: 'Maintenance 🔩'
      labels:
        - 'CD 🏗️'
        - 'CI 🦾'
        - 'production 🎭'
        - 'development 💻'
        - 'test 🧪'
        - 'maintenance 🔧'

    - title: Other Changes
      labels:
        - '*'